import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, Download, ShieldCheck, Wrench } from 'lucide-react'

const catalog = {
  'ka-id20': { name: 'KA-ID20 Cordless Impact Driver 20V', category: 'Impact Tools', description: 'A compact, high-torque impact driver built for fast fastening on site, in the workshop, and everywhere work takes you.', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1400&auto=format&fit=crop', specs: ['20V brushless motor', '1/4” hex chuck', '2.000 RPM no-load speed', 'LED work light'] },
  'ka-iw20p': { name: 'KA-IW20 Pro Impact Wrench 1/2” 20V', category: 'Impact Tools', description: 'Professional-grade cordless power for demanding fastening jobs, with dependable torque and balanced handling.', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=1400&auto=format&fit=crop', specs: ['20V brushless motor', '1/2” square drive', '450 Nm max torque', 'Variable speed trigger'] },
  'ka-rs20': { name: 'KA-RS20 Cordless Reciprocating Saw', category: 'Reciprocating Saw', description: 'Cut through timber, metal, and renovation materials with a stable cordless saw designed for control.', image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?q=80&w=1400&auto=format&fit=crop', specs: ['20V platform', '0–3.000 SPM', 'Tool-free blade change', 'Adjustable shoe'] },
}

export default async function ProductDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const product = catalog[slug as keyof typeof catalog] ?? catalog['ka-id20']
  return <main className="bg-white text-[#0A1628]"><section className="bg-[#0A1628] px-5 pb-16 pt-32 text-white md:px-16"><div className="mx-auto max-w-6xl"><Link href="/products" className="inline-flex items-center gap-2 text-sm font-bold text-white/65 hover:text-[#f5a200]"><ArrowLeft size={16} /> Back to products</Link><div className="mt-12 grid items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-extrabold uppercase tracking-[0.25em] text-[#f5a200]">{product.category}</p><h1 className="mt-4 text-4xl font-extrabold tracking-tight md:text-6xl">{product.name}</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-white/65">{product.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 rounded-lg bg-[#f5a200] px-5 py-3 text-sm font-extrabold text-[#0A1628]">Request a quote <ArrowRight size={16} /></Link><button className="inline-flex items-center gap-2 rounded-lg border border-white/20 px-5 py-3 text-sm font-bold"><Download size={16} /> Product sheet</button></div></div><div className="aspect-[4/3] overflow-hidden rounded-2xl"><img src={product.image} alt={product.name} className="size-full object-cover" /></div></div></div></section><section className="mx-auto grid max-w-6xl gap-12 px-5 py-16 md:px-16 lg:grid-cols-[1fr_1.2fr]"><div><p className="text-xs font-extrabold uppercase tracking-[0.25em] text-[#f5a200]">Built for the work ahead</p><h2 className="mt-3 text-3xl font-extrabold">Reliable performance, day after day.</h2><p className="mt-5 leading-relaxed text-[#667680]">Every Keywell tool is selected for professional environments where uptime, serviceability, and comfortable handling matter.</p><div className="mt-8 flex flex-col gap-4"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-[#f5a200]" /><span><b>Ready to deploy.</b><br /><small className="text-[#667680]">Inspected before every rental.</small></span></div><div className="flex gap-3"><Wrench className="shrink-0 text-[#f5a200]" /><span><b>Support included.</b><br /><small className="text-[#667680]">Practical advice from our team.</small></span></div></div></div><div><h3 className="text-xl font-extrabold">Product specifications</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{product.specs.map((spec) => <div key={spec} className="flex items-center gap-3 rounded-xl border border-[#dce4e8] p-4"><Check className="text-[#f5a200]" size={18} /><span className="text-sm font-semibold">{spec}</span></div>)}</div></div></section></main>
}
